/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityRow: typeof import('./src/components/scheduler/ActivityRow.vue')['default']
    Avatar: typeof import('./src/components/scheduler/Avatar.vue')['default']
    CalendarRow: typeof import('./src/components/scheduler/CalendarRow.vue')['default']
    ContextMenu: typeof import('./src/components/scheduler/ContextMenu.vue')['default']
    DayCell: typeof import('./src/components/scheduler/DayCell.vue')['default']
    DragPreview: typeof import('./src/components/scheduler/DragPreview.vue')['default']
    DragTooltip: typeof import('./src/components/scheduler/DragTooltip.vue')['default']
    EmptyDayCell: typeof import('./src/components/scheduler/EmptyDayCell.vue')['default']
    FilterableDropdown: typeof import('./src/components/scheduler/FilterableDropdown.vue')['default']
    MultiDayShiftGroup: typeof import('./src/components/scheduler/MultiDayShiftGroup.vue')['default']
    NotesEditDialog: typeof import('./src/components/scheduler/NotesEditDialog.vue')['default']
    ProjectGroup: typeof import('./src/components/scheduler/ProjectGroup.vue')['default']
    ProjectHeader: typeof import('./src/components/scheduler/ProjectHeader.vue')['default']
    ProjectHeaderRow: typeof import('./src/components/scheduler/ProjectHeaderRow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchedulerApp: typeof import('./src/components/scheduler/SchedulerApp.vue')['default']
    SchedulerDataTable: typeof import('./src/components/scheduler/SchedulerDataTable.vue')['default']
    SchedulerGrid: typeof import('./src/components/scheduler/SchedulerGrid.vue')['default']
    SchedulerRow: typeof import('./src/components/scheduler/SchedulerRow.vue')['default']
    SchedulerTable: typeof import('./src/components/scheduler/SchedulerTable.vue')['default']
    SchedulerToolbar: typeof import('./src/components/scheduler/SchedulerToolbar.vue')['default']
    ShiftBar: typeof import('./src/components/scheduler/ShiftBar.vue')['default']
    ShiftCreationPopup: typeof import('./src/components/scheduler/ShiftCreationPopup.vue')['default']
    UserMenu: typeof import('./src/components/scheduler/UserMenu.vue')['default']
  }
}
