# -*- coding: utf-8 -*-
"""Regenerate tests/offline/frappe_core_doctypes.json from a frappe/frappe checkout.

The offline suite has no bench and no database, so a Frappe core DocType's name
and field list are not otherwise available to it (see the KNOWN BLIND SPOT note
in test_doctype_metadata.py). This vendors the two things
test_core_doctype_collisions.py needs: every core DocType name, and the field
list of Currency, which is the one name this app reuses.

    python3 tests/offline/tools/dump_core_doctypes.py /path/to/frappe-bench/apps/frappe

Keep the output checked in. Re-run it when the Frappe version moves, and read
the test's failure message before editing the expectations by hand.
"""
import json
import os
import re
import sys
import glob

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "frappe_core_doctypes.json"))


def frappe_version(app_root):
    init = os.path.join(app_root, "frappe", "__init__.py")
    m = re.search(r'^__version__\s*=\s*"([^"]+)"', open(init, encoding="utf-8").read(), re.M)
    return m.group(1) if m else "unknown"


def main(app_root):
    pkg = os.path.join(app_root, "frappe")
    if not os.path.isdir(pkg):
        raise SystemExit("not a frappe app checkout: %s" % app_root)
    names, currency = [], None
    for path in glob.glob(os.path.join(pkg, "**", "doctype", "*", "*.json"), recursive=True):
        # A DocType's own JSON is <folder>/<folder>.json; skip the siblings.
        if os.path.basename(path)[:-5] != os.path.basename(os.path.dirname(path)):
            continue
        try:
            doc = json.load(open(path, encoding="utf-8"))
        except ValueError:
            continue
        if doc.get("doctype") != "DocType" or not doc.get("name"):
            continue
        names.append(doc["name"])
        if doc["name"] == "Currency":
            currency = {
                "module": doc.get("module"),
                "autoname": doc.get("autoname"),
                "fields": [
                    {"fieldname": f.get("fieldname"), "fieldtype": f.get("fieldtype"),
                     "reqd": int(bool(f.get("reqd")))}
                    for f in doc.get("fields", []) if f.get("fieldname")
                ],
            }
    version = frappe_version(app_root)
    out = {
        "_provenance": "Generated by tests/offline/tools/dump_core_doctypes.py from a "
                       "frappe/frappe checkout at version %s." % version,
        "frappe_version": version,
        "doctype_names": sorted(set(names)),
        "currency": currency,
    }
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(out, fh, indent=1, sort_keys=False)
        fh.write("\n")
    print("wrote %s: %d DocType names, frappe %s" % (OUT, len(out["doctype_names"]), version))


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    main(sys.argv[1])
